n = int(input())
print('*'*n, end='')
print(' '*(((n-1)*2)-1), end='')
print('*'*n)
for i in range(1, n):
    print(' '*i, end='')
    print('*', end='')
    print(' '*(n-2), end='')
    print('*', end='')
    print(' '*(((n-i-1)*2)-1), end='')
    if(i!=n-1):
        print('*', end='')
    print(' '*(n-2), end='')
    print('*', end='')
    print()
for i in range(n-2, 0, -1):
    print(' '*i, end='')
    print('*', end='')
    print(' '*(n-2), end='')
    print('*', end='')
    print(' '*(((n-i-1)*2)-1), end='')
    print('*', end='')
    print(' '*(n-2), end='')
    print('*', end='')
    print()
print('*'*n, end='')
print(' '*(((n-1)*2)-1), end='')
print('*'*n)